[package]
name = "point/sovereign"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
testez = "roblox/testez@0.4.1"
janitor = "howmanysmall/janitor@1.18.3"
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.1.0"
networker = "leifstout/networker@0.3.0"